name: AutoRelease

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build iOS
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
